# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='images/myimages/%Y/%m/%d')),
                ('content', models.TextField()),
            ],
        ),
    ]
