# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:23
from __future__ import unicode_literals

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_detail',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, upload_to='static/images/myimages/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='static/images/myimages/%Y/%m/%d'),
        ),
    ]
