# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_remove_article_image_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='static/media/%Y/%m/%d'),
        ),
    ]
