# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0005_auto_20171020_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='images/media'),
        ),
    ]
