# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('fruit', '0006_auto_20171020_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('image_icon', django_thumbs.db.models.ImageWithThumbsField(upload_to='static/images')),
                ('image_content1', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images')),
                ('image_content2', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images')),
                ('image_content3', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
                ('content', models.TextField(verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('kinds', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u6c34\u679c',
                'verbose_name_plural': '\u6c34\u679c',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='images/media')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
