# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0007_auto_20171027_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images/activity')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247,\u5efa\u8bae\u5927\u5c0f(800x500)',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247,\u5efa\u8bae\u5927\u5c0f(800x500)',
            },
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_content1',
            field=django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images/app'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_content2',
            field=django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images/app'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_content3',
            field=django_thumbs.db.models.ImageWithThumbsField(null=True, upload_to='static/images/app'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image_icon',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='static/images/app'),
        ),
    ]
