# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0010_auto_20171029_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247,\u4e3a\u4e86\u7f8e\u89c2\uff0c\u56fe\u7247\u5927\u5c0f\u4e0d\u8981\u76f8\u5dee\u592a\u591a', 'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247,\u4e3a\u4e86\u7f8e\u89c2\uff0c\u56fe\u7247\u5927\u5c0f\u4e0d\u8981\u76f8\u5dee\u592a\u591a'},
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='\u53cc\u5341\u4e00\u6d3b\u52a8', max_length=100, verbose_name='\u6d3b\u52a8\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits_in_activity', to='fruit.Activity', verbose_name='\u53c2\u52a0\u7684\u6d3b\u52a8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='kinds',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='\u6c34\u679c\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(blank=True, verbose_name='\u7b80\u4ecb(\u5efa\u8bae\u4e3a\u7a7a)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u89c6\u9891\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='static/media', verbose_name='\u8def\u5f84'),
        ),
    ]
