# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0011_auto_20171101_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '\u9996\u9875\u6700\u65b0\u6d3b\u52a8\u56fe\u7247,\u4e3a\u4e86\u7f8e\u89c2\uff0c\u56fe\u7247\u5927\u5c0f\u4e0d\u8981\u76f8\u5dee\u592a\u591a', 'verbose_name_plural': '\u9996\u9875\u6700\u65b0\u6d3b\u52a8\u56fe\u7247,\u4e3a\u4e86\u7f8e\u89c2\uff0c\u56fe\u7247\u5927\u5c0f\u4e0d\u8981\u76f8\u5dee\u592a\u591a'},
        ),
    ]
